/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dungeon;

import destiny.Kezdo;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author ewulusen
 */
public class CharSelector extends javax.swing.JFrame {
public static int CharakterId;
public static int DungeonFloor;
public static int DungeonID;
public static int szint=1;
public static String[][] Hexa = new String[40][];

    /**
     * Creates new form CharSelector
     */
    public CharSelector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        valaszt1 = new javax.swing.JRadioButton();
        valaszt2 = new javax.swing.JRadioButton();
        jOptionPane2 = new javax.swing.JOptionPane();
        valaszt3 = new javax.swing.JRadioButton();
        valaszt4 = new javax.swing.JRadioButton();
        valaszt5 = new javax.swing.JRadioButton();
        Img1 = new javax.swing.JLabel();
        Char1 = new javax.swing.JLabel();
        Img2 = new javax.swing.JLabel();
        Char2 = new javax.swing.JLabel();
        Img3 = new javax.swing.JLabel();
        Img4 = new javax.swing.JLabel();
        Img5 = new javax.swing.JLabel();
        Char3 = new javax.swing.JLabel();
        Char4 = new javax.swing.JLabel();
        Char5 = new javax.swing.JLabel();
        Valaszt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        id2 = new javax.swing.JLabel();
        id3 = new javax.swing.JLabel();
        id4 = new javax.swing.JLabel();
        id5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(valaszt1);
        valaszt1.setText("Választ");

        buttonGroup1.add(valaszt2);
        valaszt2.setText("Választ");

        jOptionPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 204)));
        jOptionPane2.setForeground(new java.awt.Color(255, 0, 51));
        jOptionPane2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UDPapg.gif"))); // NOI18N
        jOptionPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jOptionPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        buttonGroup1.add(valaszt3);
        valaszt3.setText("Választ");

        buttonGroup1.add(valaszt4);
        valaszt4.setText("Választ");

        buttonGroup1.add(valaszt5);
        valaszt5.setText("Választ");

        Img1.setText("-");

        Char1.setText("-");

        Img2.setText("-");

        Char2.setText("-");

        Img3.setText("-");

        Img4.setText("-");

        Img5.setText("-");

        Char3.setText("-");

        Char4.setText("-");

        Char5.setText("-");

        Valaszt.setText("Ő Lesz az!");
        Valaszt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValasztMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Kocsma");
        jLabel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        id1.setEnabled(false);
        id1.setFocusable(false);

        id2.setEnabled(false);
        id2.setFocusable(false);

        id3.setEnabled(false);
        id3.setFocusable(false);

        id4.setEnabled(false);
        id4.setFocusable(false);

        id5.setEnabled(false);
        id5.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id1)
                    .addComponent(id2)
                    .addComponent(id3)
                    .addComponent(id4)
                    .addComponent(id5))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Valaszt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jOptionPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Char1)
                                .addComponent(Char2)
                                .addComponent(Char3)
                                .addComponent(Char4)
                                .addComponent(Char5))
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Img4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valaszt4))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Img3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valaszt3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Img2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valaszt2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Img1, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                                    .addGap(35, 35, 35)
                                    .addComponent(valaszt1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Img5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valaszt5))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(105, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(id1)
                .addGap(36, 36, 36)
                .addComponent(id2)
                .addGap(42, 42, 42)
                .addComponent(id3)
                .addGap(44, 44, 44)
                .addComponent(id4)
                .addGap(34, 34, 34)
                .addComponent(id5)
                .addGap(18, 18, 18)
                .addComponent(jOptionPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Valaszt)
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valaszt1)
                        .addComponent(Img1)
                        .addComponent(Char1))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valaszt2)
                        .addComponent(Img2)
                        .addComponent(Char2))
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valaszt3)
                        .addComponent(Img3)
                        .addComponent(Char3))
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valaszt4)
                        .addComponent(Img4)
                        .addComponent(Char4))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valaszt5)
                        .addComponent(Img5)
                        .addComponent(Char5))
                    .addContainerGap(209, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOptionPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jOptionPane2AncestorAdded

    }//GEN-LAST:event_jOptionPane2AncestorAdded

    private void ValasztMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValasztMouseClicked

        if(valaszt1.isSelected())
        {
            if(id1.getText().equals("")){
                jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2.ERROR_MESSAGE,jOptionPane2.getIcon());
            }
            else {
                this.dispose();
                CharakterId=Integer.parseInt(id1.getText());
                new Quest().setVisible(true);
            }
        }
        if(valaszt2.isSelected())
        {
            if(id2.getText().equals("")){
                jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon());
            }
            else {
                this.dispose();
                CharakterId=Integer.parseInt(id2.getText());
                new Quest().setVisible(true);
            }

        }
        if(valaszt3.isSelected())
        {
            if(id3.getText().equals("")){
                jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon());
            }
            else {
                this.dispose();
                CharakterId=Integer.parseInt(id3.getText());
                new Quest().setVisible(true);
            }

        }
        if(valaszt4.isSelected())
        {
            if(id4.getText().equals("")){
                jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon());
            }
            else {
                this.dispose();
                CharakterId=Integer.parseInt(id4.getText());
                new Quest().setVisible(true);
            }

        }
        if(valaszt5.isSelected())
        {
            if(id5.getText().equals("")){
                jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon());
            }
            else {
                this.dispose();
                CharakterId=Integer.parseInt(id5.getText());
                
                new Quest().setVisible(true);
            }

                   
        }
        try {
                    DungeonID=DungeonMaker.DungeonID(CharakterId);
                    DungeonFloor=DungeonMaker.DungeonFloor();
                    Hexa=DungeonMaker.DungeonHexaCalbirate(DungeonID,szint,1,1);
                } catch (SQLException ex) {
                    System.out.println("hiba a charválasztásnál");
            Logger.getLogger(Quest.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
                

    }//GEN-LAST:event_ValasztMouseClicked

    private void jLabel3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel3AncestorAdded
        jOptionPane2.setVisible(false);
        // destiny.Connector conn=new Connector();
        int i=1;
        try {
            Statement stmt=destiny.Kezdo.conn.conn.createStatement();
            String sql="SELECT * from KARAKTERL WHERE K_KIE='"+Kezdo.playerID+"'";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next()) {
                switch (i){
                    case 1:Char1.setText(rs.getString("K_NEV"));
                    String path=getClass().getProtectionDomain().getCodeSource().getLocation().toString();
                    //System.out.println(path);
                    ImageIcon image = new  ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));
                    Img1.setText("");
                    Img1.setIcon(image);
                    id1.setText(rs.getString("KAR_ID"));
                    id1.setVisible(false);
                    break;
                    case 2:Char2.setText(rs.getString("K_NEV"));
                    image = new ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));
                    Img2.setText("");
                    Img2.setIcon(image);
                    id2.setText(rs.getString("KAR_ID"));
                    id2.setVisible(false);
                    break;
                    case 3:Char3.setText(rs.getString("K_NEV"));
                    image = new ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));
                    Img3.setText("");
                    Img3.setIcon(image);
                    id3.setText(rs.getString("KAR_ID"));
                    id3.setVisible(false);
                    break;
                    case 4:Char4.setText(rs.getString("K_NEV"));
                    image = new ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));
                    Img4.setText("");
                    Img4.setIcon(image);
                    id4.setText(rs.getString("KAR_ID"));
                    id4.setVisible(false);
                    break;
                    case 5:Char5.setText(rs.getString("K_NEV"));
                    image = new ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));
                    Img5.setText("");
                    Img5.setIcon(image);
                    id5.setText(rs.getString("KAR_ID"));
                    id5.setVisible(false);
                    break;

                }
                i++;
            }
        }
        catch (Exception ex) {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_jLabel3AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Char1;
    private javax.swing.JLabel Char2;
    private javax.swing.JLabel Char3;
    private javax.swing.JLabel Char4;
    private javax.swing.JLabel Char5;
    private javax.swing.JLabel Img1;
    private javax.swing.JLabel Img2;
    private javax.swing.JLabel Img3;
    private javax.swing.JLabel Img4;
    private javax.swing.JLabel Img5;
    private javax.swing.JButton Valaszt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel id2;
    private javax.swing.JLabel id3;
    private javax.swing.JLabel id4;
    private javax.swing.JLabel id5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JRadioButton valaszt1;
    private javax.swing.JRadioButton valaszt2;
    private javax.swing.JRadioButton valaszt3;
    private javax.swing.JRadioButton valaszt4;
    private javax.swing.JRadioButton valaszt5;
    // End of variables declaration//GEN-END:variables
}
