/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CharModify;

import destiny.Kezdo;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ewulusen
 */
public class CharSuit extends javax.swing.JFrame {
public static int Capacitivy=0;
    /**
     * Creates new form CharSuit
     */
    public CharSuit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Capacitiv = new javax.swing.JLabel();
        putOn = new javax.swing.JButton();
        putDown = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArmorOnYou = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        weaponOnYou = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        neklanceOnYou = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        ringOnYou = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Páncél");

        jLabel2.setText("Fegyver");

        jLabel4.setText("Nyaklánc");

        jLabel5.setText("Gyűrű");

        jLabel6.setText("teherbírás:");

        Capacitiv.setText("-");

        putOn.setText("Felvesz");
        putOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putOnActionPerformed(evt);
            }
        });

        putDown.setText("Levesz");
        putDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putDownActionPerformed(evt);
            }
        });

        ArmorOnYou.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ArmorOnYou.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ArmorOnYouAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ArmorOnYou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArmorOnYouMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ArmorOnYou);
        ArmorOnYou.getAccessibleContext().setAccessibleParent(ArmorOnYou);

        weaponOnYou.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        weaponOnYou.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                weaponOnYouAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        weaponOnYou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weaponOnYouMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(weaponOnYou);
        weaponOnYou.getAccessibleContext().setAccessibleParent(ArmorOnYou);

        neklanceOnYou.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        neklanceOnYou.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                neklanceOnYouAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        neklanceOnYou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                neklanceOnYouMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(neklanceOnYou);
        neklanceOnYou.getAccessibleContext().setAccessibleParent(ArmorOnYou);

        ringOnYou.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ringOnYou.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ringOnYouAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ringOnYou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ringOnYouMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(ringOnYou);
        ringOnYou.getAccessibleContext().setAccessibleParent(ArmorOnYou);

        jButton1.setText("Mégsem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Hátitáska:");

        jList1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jList1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane6.setViewportView(jList1);

        jList2.setEnabled(false);
        jScrollPane7.setViewportView(jList2);

        jList3.setEnabled(false);
        jScrollPane8.setViewportView(jList3);

        jList4.setEnabled(false);
        jScrollPane9.setViewportView(jList4);

        jList5.setEnabled(false);
        jScrollPane10.setViewportView(jList5);

        jList6.setEnabled(false);
        jScrollPane11.setViewportView(jList6);

        jList7.setEnabled(false);
        jScrollPane12.setViewportView(jList7);

        jLabel9.setText("Név");

        jLabel10.setText("Ár");

        jLabel11.setText("Súly");

        jLabel12.setText("Mit");

        jLabel13.setText("Mennyit");

        jLabel14.setText("AC");

        jLabel15.setText("DMG");

        jScrollPane13.setViewportView(jList8);

        jList9.setEnabled(false);
        jScrollPane5.setViewportView(jList9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Capacitiv))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(putOn)
                            .addComponent(putDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel11)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel12)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel14)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Capacitiv))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(putOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(putDown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArmorOnYouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArmorOnYouMouseClicked
        ArmorOnYou.setEnabled(true);
        weaponOnYou.setEnabled(false);
        neklanceOnYou.setEnabled(false);
        ringOnYou.setEnabled(false);
        ArmorOnYou.setFocusable(true);
        weaponOnYou.setFocusable(false);
        neklanceOnYou.setFocusable(false);
        ringOnYou.setFocusable(false);
    }//GEN-LAST:event_ArmorOnYouMouseClicked

    private void weaponOnYouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weaponOnYouMouseClicked
        ArmorOnYou.setEnabled(false);
        weaponOnYou.setEnabled(true);
        neklanceOnYou.setEnabled(false);
        ringOnYou.setEnabled(false);
         ArmorOnYou.setFocusable(false);
        weaponOnYou.setFocusable(true);
        neklanceOnYou.setFocusable(false);
        ringOnYou.setFocusable(false);
    }//GEN-LAST:event_weaponOnYouMouseClicked

    private void ringOnYouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ringOnYouMouseClicked
        ArmorOnYou.setEnabled(false);
        weaponOnYou.setEnabled(false);
        neklanceOnYou.setEnabled(false);
        ringOnYou.setEnabled(true);
        ArmorOnYou.setFocusable(false);
        weaponOnYou.setFocusable(false);
        neklanceOnYou.setFocusable(false);
        ringOnYou.setFocusable(true);
    }//GEN-LAST:event_ringOnYouMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false); //this will close frame i.e. NewJFrame
       new CharSuit().setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ArmorOnYouAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ArmorOnYouAncestorAdded
       int fegyver=0;
        try {
           fegyver=pointSetter.pointSetter1("K_ARMOR", Charakters.CharakterId);
           Statement stmt=Kezdo.conn.conn.createStatement();
           String sql="SELECT * from PANCEL WHERE P_ID='"+fegyver+"'";
           ResultSet rs1=stmt.executeQuery(sql);
           rs1.next();
           DefaultListModel model = new DefaultListModel();
              if(fegyver==0) {
           String itemCode = "nincs iylen tárgyad"; //get the element in column "item_code"
           model.addElement(itemCode); 
           }
              else {
           String itemCode = rs1.getString("P_NEV"); //get the element in column "item_code"
           model.addElement(itemCode); //add each item to the model
              
           Capacitivy=Capacitivy+Integer.parseInt(rs1.getString("P_KG"));
           }
        
      ArmorOnYou.setModel(model);
           
        } catch (SQLException ex) {
            Logger.getLogger(CharSuit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ArmorOnYouAncestorAdded

    private void neklanceOnYouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_neklanceOnYouMouseClicked
        ArmorOnYou.setEnabled(false);
        weaponOnYou.setEnabled(false);
        neklanceOnYou.setEnabled(true);
        ringOnYou.setEnabled(false);
           ArmorOnYou.setFocusable(false);
        weaponOnYou.setFocusable(false);
        neklanceOnYou.setFocusable(true);
        ringOnYou.setFocusable(false);
    }//GEN-LAST:event_neklanceOnYouMouseClicked

    private void weaponOnYouAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_weaponOnYouAncestorAdded
        int fegyver=0;
        try {
           fegyver=pointSetter.pointSetter1("K_WEAPONS", Charakters.CharakterId);
           Statement stmt=Kezdo.conn.conn.createStatement();
           String sql="SELECT * from FEGYVEREK WHERE F_ID='"+fegyver+"'";
           ResultSet rs1=stmt.executeQuery(sql);
           rs1.next();
           DefaultListModel model = new DefaultListModel();
           if(fegyver==0) {
           String itemCode = "nincs iylen tárgyad"; //get the element in column "item_code"
           model.addElement(itemCode); 
           }
           else {
           String itemCode = rs1.getString("F_NEV"); //get the element in column "item_code"
           model.addElement(itemCode); //add each item to the model
           
           Capacitivy=Capacitivy+Integer.parseInt(rs1.getString("F_KG"));
        }
      weaponOnYou.setModel(model);
           
        } catch (SQLException ex) {
            Logger.getLogger(CharSuit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_weaponOnYouAncestorAdded

    private void neklanceOnYouAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_neklanceOnYouAncestorAdded
        int fegyver=0;
        String itemCode;
        try {
            DefaultListModel model = new DefaultListModel();
           fegyver=pointSetter.pointSetter1("K_NYAKLANC", Charakters.CharakterId);
           Statement stmt=Kezdo.conn.conn.createStatement();
           String sql="SELECT * from NYAKLANC WHERE NY_ID='"+fegyver+"'";
           ResultSet rs1=stmt.executeQuery(sql);
           rs1.next();
           
           if(fegyver==0) {
           itemCode = "nincs iylen tárgyad"; //get the element in column "item_code"
           model.addElement(itemCode); 
           }
           else {
           itemCode = rs1.getString("NY_NEV"); //get the element in column "item_code"
           model.addElement(itemCode); //add each item to the model
           
           Capacitivy=Capacitivy+Integer.parseInt(rs1.getString("NY_KG"));
           }
      neklanceOnYou.setModel(model);
           
        } catch (SQLException ex) {
            Logger.getLogger(CharSuit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_neklanceOnYouAncestorAdded

    private void ringOnYouAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ringOnYouAncestorAdded
             int fegyver=0;
        try {
           fegyver=pointSetter.pointSetter1("K_GYURU", Charakters.CharakterId);
           Statement stmt=Kezdo.conn.conn.createStatement();
          
           String sql="SELECT * from GYURUK WHERE GY_ID='"+fegyver+"'";
           ResultSet rs1=stmt.executeQuery(sql);
           rs1.next();
           DefaultListModel model = new DefaultListModel();
            if(fegyver==0) {
           String itemCode = "nincs iylen tárgyad"; //get the element in column "item_code"
           model.addElement(itemCode); 
           }
           else {
           String itemCode = rs1.getString("GY_NEV"); //get the element in column "item_code"
           model.addElement(itemCode); //add each item to the model
           
           Capacitivy=Capacitivy+Integer.parseInt(rs1.getString("GY_KG"));
            }
      ringOnYou.setModel(model);
           
        } catch (SQLException ex) {
            Logger.getLogger(CharSuit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ringOnYouAncestorAdded

    private void putOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putOnActionPerformed
    try {
        String id;
        ResultSet rs;
        String mit;
        String mire;
        String jel;
        int selected;
        
        
        
        id=jList8.getModel().getElementAt(jList1.getSelectedIndex()).toString();           
        jel=jList9.getModel().getElementAt(jList1.getSelectedIndex()).toString();
        //System.out.println("id: "+id+" jel: "+jel);
        pointSetter.putOn(id,jel,Charakters.CharakterId);
       this.setVisible(false); //this will close frame i.e. NewJFrame
       new CharSuit().setVisible(true);   
    } catch (Exception ex) {
        System.out.println("baj van a a felvételnél: "+ex);
    }
       
    }//GEN-LAST:event_putOnActionPerformed

    private void jList1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jList1AncestorAdded
      String nev=null;
    String ar=null;
    String suly=null;
    String mit=null;
    String mennyi=null;
    String ac=null;
    String dmg=null;
    String jel=null;
    ResultSet rs;
    String itemCode=null;
        try {
        DefaultListModel modeln = new DefaultListModel();
        DefaultListModel modela = new DefaultListModel();
        DefaultListModel models = new DefaultListModel();
        DefaultListModel modelm = new DefaultListModel();
        DefaultListModel modelmm = new DefaultListModel();
        DefaultListModel modelac = new DefaultListModel();
        DefaultListModel modeldmg = new DefaultListModel();
        DefaultListModel modelid = new DefaultListModel();
        DefaultListModel modelj = new DefaultListModel();
        Statement stmt=Kezdo.conn.conn.createStatement();
         Statement stmt1=Kezdo.conn.conn.createStatement();
        String sql="SELECT * from ITEMEK WHERE I_PID='"+Charakters.CharakterId+"' and I_ON='0'";
        ResultSet rs1=stmt.executeQuery(sql);
        while(rs1.next()) {
            jel=rs1.getString("I_FAJ");
            itemCode=rs1.getString("I_ID");
            if(rs1.getString("I_FAJ").equals("F")){
           sql="SELECT * from  FEGYVEREK where F_ID='"+rs1.getString("I_FID")+"'";
           rs=stmt1.executeQuery(sql);
           rs.next();
           nev=rs.getString("F_NEV");

           ar=rs.getString("F_AR");
          
           suly= rs.getString("F_KG");
            
           mit=rs.getString("F_MIT");
           
           mennyi= rs.getString("F_SZAM"); 
           
           ac="0";
          
           dmg= rs.getString("F_DMG");
           
          
          
        
           Capacitivy=Capacitivy+Integer.parseInt(rs.getString("F_KG"));
                   }
              if(rs1.getString("I_FAJ").equals("P")){
            sql="SELECT * from  PANCEL where P_ID='"+rs1.getString("I_FID")+"'";
           rs=stmt1.executeQuery(sql);
           rs.next();
           nev=rs.getString("P_NEV");
           ar=rs.getString("P_AR");
           suly= rs.getString("P_KG");       
           mit=rs.getString("P_MIT");
           mennyi= rs.getString("P_SZAM");       
           ac=rs.getString("P_AC");
           dmg="0";    
           Capacitivy=Capacitivy+Integer.parseInt(rs.getString("P_KG"));
          
                   }
           if(rs1.getString("I_FAJ").equals("NY")){
          sql="SELECT * from  NYAKLANC where NY_ID='"+rs1.getString("I_FID")+"'";
           rs=stmt1.executeQuery(sql);
           rs.next();
           nev=rs.getString("NY_NEV");
           ar=rs.getString("NY_AR");
           suly= rs.getString("NY_KG");       
           mit=rs.getString("NY_MIT");
           mennyi= rs.getString("NY_SZAM");       
           ac="0";
           dmg="0";  
           Capacitivy=Capacitivy+Integer.parseInt(rs.getString("NY_KG"));
          
                   }
           if(rs1.getString("I_FAJ").equals("GY")){
           sql="SELECT * from  GYURUK where GY_ID='"+rs1.getString("I_FID")+"'";
           rs=stmt1.executeQuery(sql);
           rs.next();
           nev=rs.getString("GY_NEV");
           ar=rs.getString("GY_AR");
           suly= rs.getString("GY_KG");       
           mit=rs.getString("GY_MIT");
           mennyi= rs.getString("GY_SZAM");       
           ac="0";
           dmg="0";   
           Capacitivy=Capacitivy+Integer.parseInt(rs.getString("GY_KG"));
           
                   }
            /*if(rs1.getString("I_FAJ").equals("PO")){
           sql="SELECT * from  POTION where PO_ID='"+rs1.getString("I_FID")+"'";
           rs=stmt1.executeQuery(sql);
           rs.next();
           nev=rs.getString("PO_NEV");
           ar=rs.getString("PO_AR");
           suly= rs.getString("PO_KG");       
           mit=rs.getString("PO_MIT");
           mennyi= rs.getString("PO_SZAM");       
           ac="0";
           dmg="0"; 
           Capacitivy=Capacitivy+Integer.parseInt(rs.getString("PO_KG"));
                   }*/
          modeln.addElement(nev); modela.addElement(ar);models.addElement(suly);modelm.addElement(mit);
          modelmm.addElement(mennyi);modeldmg.addElement(dmg); modelac.addElement(ac); modelid.addElement(itemCode);modelj.addElement(jel);
        jList1.setModel(modeln);
        jList2.setModel(modela);
        jList3.setModel(models);
        jList4.setModel(modelm);
        jList5.setModel(modelmm); 
        jList6.setModel(modelac);
        jList7.setModel(modeldmg);
        jList8.setModel(modelid);
        jList9.setModel(modelj);
        
        }
    } catch (Exception ex) {
      System.out.println("baj van a tablenél: "+ex);
    }
        Capacitiv.setText(Integer.toString((pointSetter.pointSetter1("K_ASTR", Charakters.CharakterId)*10)-(Capacitivy)));
    }//GEN-LAST:event_jList1AncestorAdded

    private void putDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putDownActionPerformed
          String Armor;
         String Weapon;
         String Neklanc;
         String Ring;
         String jel = null;
       
     
       if(ArmorOnYou.getSelectedValue().equals("")) {
           
       }
       else {
           Armor= ArmorOnYou.getSelectedValue().toString();
              try {
                  Statement stmt=Kezdo.conn.conn.createStatement();
                  String sql="SELECT * from PANCEL WHERE P_NEV='"+Armor+"'";
                  ResultSet rs1=stmt.executeQuery(sql);
                  while(rs1.next()) {
                      jel=rs1.getString("P_ID");
                  }
                  pointSetter.putDown(jel, "P", Charakters.CharakterId);
                  this.setVisible(false);
                  new CharSuit().setVisible(true);
              } catch (SQLException ex) {
                  Logger.getLogger(CharSuit.class.getName()).log(Level.SEVERE, null, ex);
              }
       }
             if(weaponOnYou.getSelectedValue().equals("")) {
           
       }
       else {
           Weapon= weaponOnYou.getSelectedValue().toString();
              try {
                  Statement stmt=Kezdo.conn.conn.createStatement();
                  String sql="SELECT * from FEGYVEREK WHERE F_NEV='"+Weapon+"'";
                  ResultSet rs1=stmt.executeQuery(sql);
                  while(rs1.next()) {
                      jel=rs1.getString("F_ID");
                  }
                  pointSetter.putDown(jel, "F", Charakters.CharakterId);
                  this.setVisible(false);
                  new CharSuit().setVisible(true);
              } catch (SQLException ex) {
                  Logger.getLogger(CharSuit.class.getName()).log(Level.SEVERE, null, ex);
              }
       }
                   if(neklanceOnYou.getSelectedValue().equals("")) {
           
       }
       else {
           Neklanc= neklanceOnYou.getSelectedValue().toString();
              try {
                  Statement stmt=Kezdo.conn.conn.createStatement();
                  String sql="SELECT * from NYAKLANC WHERE NY_NEV='"+Neklanc+"'";
                  ResultSet rs1=stmt.executeQuery(sql);
                  while(rs1.next()) {
                      jel=rs1.getString("NY_ID");
                  }
                  pointSetter.putDown(jel, "NY", Charakters.CharakterId);
                  this.setVisible(false);
                  new CharSuit().setVisible(true);
              } catch (SQLException ex) {
                  Logger.getLogger(CharSuit.class.getName()).log(Level.SEVERE, null, ex);
              }
              
       }
      if(ringOnYou.getSelectedValue().equals("")) {
           
       }
       else {
           Ring= ringOnYou.getSelectedValue().toString();
              try {
                  Statement stmt=Kezdo.conn.conn.createStatement();
                  String sql="SELECT * from GYURUK WHERE GY_NEV='"+Ring+"'";
                  ResultSet rs1=stmt.executeQuery(sql);
                  while(rs1.next()) {
                      jel=rs1.getString("GY_ID");
                  }
                  pointSetter.putDown(jel, "GY", Charakters.CharakterId);
                  this.setVisible(false);
                  new CharSuit().setVisible(true);
              } catch (SQLException ex) {
                  Logger.getLogger(CharSuit.class.getName()).log(Level.SEVERE, null, ex);
              }
       }
    }//GEN-LAST:event_putDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharSuit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharSuit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharSuit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharSuit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharSuit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ArmorOnYou;
    private javax.swing.JLabel Capacitiv;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JList jList6;
    private javax.swing.JList jList7;
    private javax.swing.JList jList8;
    private javax.swing.JList jList9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList neklanceOnYou;
    private javax.swing.JButton putDown;
    private javax.swing.JButton putOn;
    private javax.swing.JList ringOnYou;
    private javax.swing.JList weaponOnYou;
    // End of variables declaration//GEN-END:variables
}
