/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CharModify;

import destiny.Kezdo;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author ewulusen
 */
public class Charakters extends javax.swing.JFrame {
public static int CharakterId;
    /**
     * Creates new form Charakters
     */
    public Charakters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        valaszt1 = new javax.swing.JRadioButton();
        valaszt2 = new javax.swing.JRadioButton();
        valaszt3 = new javax.swing.JRadioButton();
        valaszt4 = new javax.swing.JRadioButton();
        valaszt5 = new javax.swing.JRadioButton();
        Img1 = new javax.swing.JLabel();
        Char1 = new javax.swing.JLabel();
        Img2 = new javax.swing.JLabel();
        Char2 = new javax.swing.JLabel();
        Img3 = new javax.swing.JLabel();
        Img4 = new javax.swing.JLabel();
        Img5 = new javax.swing.JLabel();
        Char3 = new javax.swing.JLabel();
        Char4 = new javax.swing.JLabel();
        Char5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        id1 = new javax.swing.JLabel();
        id2 = new javax.swing.JLabel();
        id3 = new javax.swing.JLabel();
        id4 = new javax.swing.JLabel();
        id5 = new javax.swing.JLabel();
        jOptionPane2 = new javax.swing.JOptionPane();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kocsma");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        buttonGroup1.add(valaszt1);
        valaszt1.setText("Választ");

        buttonGroup1.add(valaszt2);
        valaszt2.setText("Választ");

        buttonGroup1.add(valaszt3);
        valaszt3.setText("Választ");

        buttonGroup1.add(valaszt4);
        valaszt4.setText("Választ");

        buttonGroup1.add(valaszt5);
        valaszt5.setText("Választ");

        Img1.setText("-");

        Char1.setText("-");

        Img2.setText("-");

        Char2.setText("-");

        Img3.setText("-");

        Img4.setText("-");

        Img5.setText("-");

        Char3.setText("-");

        Char4.setText("-");

        Char5.setText("-");

        jButton1.setText("Tanít");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Pontok elosztása");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Megnézem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        id1.setEnabled(false);
        id1.setFocusable(false);

        id2.setEnabled(false);

        id3.setEnabled(false);

        id4.setEnabled(false);

        id5.setEnabled(false);

        jOptionPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 204)));
        jOptionPane2.setForeground(new java.awt.Color(255, 0, 51));
        jOptionPane2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UDPapg.gif"))); // NOI18N
        jOptionPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jOptionPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton4.setText("Öltöző");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Piac");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(id1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(id2)
                                    .addGap(18, 18, 18)
                                    .addComponent(id3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(id4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(id5)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jOptionPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Char1)
                            .addComponent(Char2)
                            .addComponent(Char3)
                            .addComponent(Char4)
                            .addComponent(Char5))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Img4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valaszt4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Img3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valaszt3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Img2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valaszt2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Img1, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                                .addGap(35, 35, 35)
                                .addComponent(valaszt1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Img5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valaszt5)))
                        .addGap(74, 74, 74)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valaszt1)
                    .addComponent(Img1)
                    .addComponent(Char1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valaszt2)
                    .addComponent(Img2)
                    .addComponent(Char2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valaszt3)
                    .addComponent(Img3)
                    .addComponent(Char3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valaszt4)
                    .addComponent(Img4)
                    .addComponent(Char4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valaszt5)
                    .addComponent(Img5)
                    .addComponent(Char5))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id1)
                            .addComponent(id2)
                            .addComponent(id3)
                            .addComponent(id4)
                            .addComponent(id5))
                        .addGap(0, 236, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(18, 18, 18)
                        .addComponent(jOptionPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
       jOptionPane2.setVisible(false);
    // destiny.Connector conn=new Connector();
      int i=1;
        try {
        Statement stmt=destiny.Kezdo.conn.conn.createStatement();
            String sql="SELECT * from KARAKTERL WHERE K_KIE='"+Kezdo.playerID+"'";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next()) {
                switch (i){
                    case 1:Char1.setText(rs.getString("K_NEV"));
                    String path=getClass().getProtectionDomain().getCodeSource().getLocation().toString();
                    //System.out.println(path);
                    ImageIcon image = new  ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));
                    Img1.setText("");
                    Img1.setIcon(image);
                    id1.setText(rs.getString("KAR_ID"));
                    id1.setVisible(false);
                            break;
                    case 2:Char2.setText(rs.getString("K_NEV"));
                    image = new ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));       
                    Img2.setText("");       
                    Img2.setIcon(image);
                    id2.setText(rs.getString("KAR_ID"));
                    id2.setVisible(false);
                            break; 
                    case 3:Char3.setText(rs.getString("K_NEV"));
                    image = new ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));       
                    Img3.setText("");    
                    Img3.setIcon(image);
                    id3.setText(rs.getString("KAR_ID"));
                    id3.setVisible(false);
                        break;
                    case 4:Char4.setText(rs.getString("K_NEV"));
                    image = new ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));       
                    Img4.setText(""); 
                    Img4.setIcon(image);
                    id4.setText(rs.getString("KAR_ID"));
                    id4.setVisible(false);
                            break;
                    case 5:Char5.setText(rs.getString("K_NEV"));
                   image = new ImageIcon(getClass().getResource("/images/"+rs.getString("KAR_FAJ")+rs.getString("KAR_KASZT")+"g.gif" ));       
                   Img5.setText(""); 
                   Img5.setIcon(image);
                   id5.setText(rs.getString("KAR_ID"));
                   id5.setVisible(false);
                            break;
                        
                }
            i++;
       }
      }
      catch (Exception ex) {
            System.out.println("Error: "+ex);
            }
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        if(valaszt1.isSelected())
        {   
            if(id1.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2.ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id1.getText());
           new CharLearn().setVisible(true);
        }
        }
          if(valaszt2.isSelected())
        {
                   if(id2.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id2.getText());
           new CharLearn().setVisible(true);
        }
            
        }
            if(valaszt3.isSelected())
        {
                   if(id3.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id3.getText());
           new CharLearn().setVisible(true);
        }
       
        }
              if(valaszt4.isSelected())
        {
                   if(id4.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id4.getText());
           new CharLearn().setVisible(true);
        }
         
        }
                if(valaszt5.isSelected())
        {
                   if(id5.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id5.getText());
           new CharLearn().setVisible(true);
        }
            
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jOptionPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jOptionPane2AncestorAdded

    }//GEN-LAST:event_jOptionPane2AncestorAdded

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
            this.dispose();
             if(valaszt1.isSelected())
        {   
            if(id1.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2.ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id1.getText());
           new CharPointSetter().setVisible(true);
        }
        }
          if(valaszt2.isSelected())
        {
                   if(id2.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id2.getText());
           new CharPointSetter().setVisible(true);
        }
            
        }
            if(valaszt3.isSelected())
        {
                   if(id3.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id3.getText());
           new CharPointSetter().setVisible(true);
        }
       
        }
              if(valaszt4.isSelected())
        {
                   if(id4.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id4.getText());
          new CharPointSetter().setVisible(true);
        }
         
        }
                if(valaszt5.isSelected())
        {
                   if(id5.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id5.getText());
           new CharPointSetter().setVisible(true);
        }
            
        }
            
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(valaszt1.isSelected())
        {   
            if(id1.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2.ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id1.getText());
           new CharViewer().setVisible(true);
        }
        }
          if(valaszt2.isSelected())
        {
                   if(id2.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id2.getText());
           new CharViewer().setVisible(true);
        }
            
        }
            if(valaszt3.isSelected())
        {
                   if(id3.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id3.getText());
           new CharViewer().setVisible(true);
        }
       
        }
              if(valaszt4.isSelected())
        {
                   if(id4.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id4.getText());
          new CharViewer().setVisible(true);
        }
         
        }
                if(valaszt5.isSelected())
        {
                   if(id5.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id5.getText());
           new CharViewer().setVisible(true);
        }
            
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         if(valaszt1.isSelected())
        {   
            if(id1.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2.ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id1.getText());
           new CharSuit().setVisible(true);
        }
        }
          if(valaszt2.isSelected())
        {
                   if(id2.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id2.getText());
           new CharSuit().setVisible(true);
        }
            
        }
            if(valaszt3.isSelected())
        {
                   if(id3.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id3.getText());
           new CharSuit().setVisible(true);
        }
       
        }
              if(valaszt4.isSelected())
        {
                   if(id4.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id4.getText());
          new CharSuit().setVisible(true);
        }
         
        }
                if(valaszt5.isSelected())
        {
                   if(id5.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id5.getText());
           new CharSuit().setVisible(true);
        }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(valaszt1.isSelected())
        {   
            if(id1.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2.ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id1.getText());
           new Market().setVisible(true);
        }
        }
          if(valaszt2.isSelected())
        {
                   if(id2.getText().equals("")){
            jOptionPane2.showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id2.getText());
           new Market().setVisible(true);
        }
            
        }
            if(valaszt3.isSelected())
        {
                   if(id3.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id3.getText());
           new Market().setVisible(true);
        }
       
        }
              if(valaszt4.isSelected())
        {
                   if(id4.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id4.getText());
          new Market().setVisible(true);
        }
         
        }
                if(valaszt5.isSelected())
        {
                   if(id5.getText().equals("")){
            jOptionPane2 .showMessageDialog(null, "Nincs ilyen karaktered!!!","Alert!", jOptionPane2 .ERROR_MESSAGE,jOptionPane2.getIcon()); 
            }
            else {
           this.dispose();
           CharakterId=Integer.parseInt(id5.getText());
           new Market().setVisible(true);
        }
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Charakters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Charakters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Charakters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Charakters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Charakters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Char1;
    private javax.swing.JLabel Char2;
    private javax.swing.JLabel Char3;
    private javax.swing.JLabel Char4;
    private javax.swing.JLabel Char5;
    private javax.swing.JLabel Img1;
    private javax.swing.JLabel Img2;
    private javax.swing.JLabel Img3;
    private javax.swing.JLabel Img4;
    private javax.swing.JLabel Img5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel id2;
    private javax.swing.JLabel id3;
    private javax.swing.JLabel id4;
    private javax.swing.JLabel id5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JRadioButton valaszt1;
    private javax.swing.JRadioButton valaszt2;
    private javax.swing.JRadioButton valaszt3;
    private javax.swing.JRadioButton valaszt4;
    private javax.swing.JRadioButton valaszt5;
    // End of variables declaration//GEN-END:variables
}
